### ISSUE TITLE
Goofy ahh rat

### ISSUE THREAD

**Issue by zLeki** [AbsoluteDevYTB/ImageTokenLogger#2]
Its a rat and it sends your information in the image below, includes camera, ip, passwords, cookies, and more
![Screen Shot 2022-03-05 at 12 57 56 PM](https://user-images.githubusercontent.com/85647342/156894848-676adf6c-05d5-4015-a5c2-807559787fc8.png)
.

**Comment by Itsdpp** [comment]
how do people can notice that i wanna learn but idk where to start

**Comment by sandyy-gmod** [comment]
Its not a RAT its a shit simple stealer

**Comment by zLeki** [comment]
I'm just saying it's harmful sorry for thr confusion

**Comment by Itsdpp** [comment]
i need a good img logger cuz i wanna use it on sum scammer that steals roblox acc from others

**Comment by zLeki** [comment]
> i need a good img logger cuz i wanna use it on sum scammer that steals roblox acc from others

Why? Why would you want to steal peoples information for no reason.

**Comment by Itsdpp** [comment]
some shitty guy with the har scam got my roblox acc but luckily  i got it back

**Comment by Itsdpp** [comment]
and i noticed that this man is just stealin a bunch of roblox acc that are probably childs and i wanted to do smth to fuck him up like stealin his discord acc

**Comment by zLeki** [comment]
> and i noticed that this man is just stealin a bunch of roblox acc that are probably childs and i wanted to do smth to fuck him up like stealin his discord acc

yeah this guy is stealing peoples passwords, credit cards, and more if you want to talk add me here Leki 6796 im closing this discussion

**Comment by sandyy-gmod** [comment]
> > how do people can notice that i wanna learn but idk where to start
> 
> I just used a http debugger

burp suite >
